---
kind: pipeline
name: compliance

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - pull_request

steps:
  - name: build
    pull: always
    image: golang:1.15
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make test
      - make build

  - name: vet
    pull: always
    image: golang:1.15
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make vet
    depends_on:
      - build

  - name: lint
    pull: always
    image: golangci/golangci-lint:v1.32
    commands:
      - golangci-lint --timeout 5m run
    depends_on:
      - build

---
kind: pipeline
name: release-main

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: build
    pull: always
    image: golang:1.15
    environment:
      GOPROXY: https://goproxy.cn
      VERSION: ${DRONE_COMMIT}
    commands:
      - make build
  - name: build-windows
    pull: always
    image: golang:1.15
    environment:
      GOPROXY: https://goproxy.cn
      VERSION: ${DRONE_COMMIT}
      GOOS: windows
    commands:
      - make build
  - name: gitea-release
    pull: always
    image: jolheiser/drone-gitea-main:latest
    environment:
      GOPROXY: https://goproxy.cn
    settings:
      token:
        from_secret: gitea_token
      base: https://gitea.com
      files:
        - "tmpl"
        - "tmpl.exe"
    depends_on:
      - build
      - build-windows


---
kind: pipeline
name: release-tag

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
    - refs/tags/*
    exclude:
    - refs/tags/latest

steps:
  - name: build
    pull: always
    image: golang:1.15
    environment:
      GOPROXY: https://goproxy.cn
      VERSION: ${DRONE_TAG}
    commands:
      - make build
  - name: build-windows
    pull: always
    image: golang:1.15
    environment:
      GOPROXY: https://goproxy.cn
      GOOS: windows
      VERSION: ${DRONE_TAG}
    commands:
      - make build
  - name: gitea-release
    pull: always
    image: plugins/gitea-release:1
    environment:
      GOPROXY: https://goproxy.cn
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://gitea.com
      files:
        - "tmpl"
        - "tmpl.exe"
    depends_on:
      - build
      - build-windows
  - name: gitea-prune
    pull: always
    image: jolheiser/drone-gitea-prune
    environment:
      GOPROXY: https://goproxy.cn
    settings:
      token:
        from_secret: gitea_token
      base: https://gitea.com
    depends_on:
      - gitea-release