clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

pipeline:
  compliance:
    image: golang:1.18
    commands:
      - go test -race ./...
      - go vet ./...
      - go run github.com/rs/zerolog/cmd/lint@latest go.jolheiser.com/tmpl
    when:
      event: pull_request

  build:
    image: goreleaser/goreleaser
    commands:
      - goreleaser build --snapshot
    when:
      event: pull_request

  release:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    secrets: [ gitea_token ]
    when:
      event: tag

  prune:
    image: jolheiser/drone-gitea-prune
    settings:
      base: https://git.jojodev.com
      token:
        from_secret: gitea_token
    when:
      event: tag
